### ISSUE TITLE
Bug: unable to login when running on localhost and Bitbucket Oauth provider

### ISSUE THREAD

**Issue by jsidney** [valentindeaconu/terralist#112]
First of all - @valentindeaconu you are a proper legend for this project!!! I have been waiting ages for something like this 😄 

I am trying to run the project locally (the plan is to deploy it via a Fargate Cluster in the near future) and use my employer's bitbucket as the oauth provider for our teams to authenticate against. 
I have set up the client and the required config in a config.yaml and I am able to launch it successfully. but when I try and run 
```
terraform login registry.example.com 
```
I get the following error:
```bash
│ Error: Service discovery failed for registry.example.com
│
│ Failed to request discovery document: Get "https://registry.example.com/.well-known/terraform.json": dial tcp: lookup registry.example.com on 172.30.192.1:53: no such host.
```
I can hit the localhost URL in my browser and create an authority etc, but I cant figure out how to hit the registry from the cli. 
Can you please assist on this? (is it just something in the docs that is missing etc or is there a bug in the code?)
I would love to contribute to the project, but my GO skills are so bad that you wouldn't want it! 
thanks again for this project @valentindeaconu !

**Comment by ArnoSen** [comment]
`registry.example.com` should be replaced with the hostname of the machine that you are running Terralist from. In your case that should then be `localhost`.

**Comment by jsidney** [comment]
thanks @ArnoSen  - so when i did use localhost -
```
terraform login localhost:5758                                                                                                                               1 ✘  at 12:17:59 ▓▒░
╷
│ Error: Service discovery failed for localhost:5758
│
│ Failed to request discovery document: Get "https://localhost:5758/.well-known/terraform.json": http: server gave HTTP response to HTTPS client.
```
its probably something stupid that I am doing?

**Comment by valentindeaconu** [comment]
Hello @jsidney, thank you for all the appreciation!

The problem you're facing is that you have to replace the endpoint as @ArnoSen suggested. There's one more problem, which now that you mention it, I notice that it's indeed missing from the documentation. The problem is that Terraform requires HTTPS for establishing the connection to the registry.

To be able to do such on your local development, you either have to create a trusted certificate and put a proxy in front of the Terralist server, which is able to expose an HTTPS endpoint or use some tooling like [ngrok](https://ngrok.com/).

After you spin up your Terralist server (let's say, on port `5758` - the default one), open a new `ngrok` instance with the command:
```
ngrok http 5758
```
Then copy the subdomain from the `ngrok` output, which should look like this:
```
...
Forwarding                    https://<some-uuid>.ngrok.io -> http://localhost:5758
...
```

The `<some-uuid>.ngrok.io` can be used to authenticate to the local Terralist server:
```
terraform login <some-uuid>.ngrok.io
```

When you close the server, don't forget to remove it form the `$HOME/.terraform.d/credentials.tfrc.json`, since that ngrok UUID is random and you will receive a new one each time you start the server.

Also, the artifacts can be accessed from Terraform in the same way:
```hcl
module "example" {
  source  = "<some-uuid>.ngrok.io/namespace/name/provider"
  version = "1.0.0"
}
```

For the rest of the API (endpoints under `/v1/api`), you can access them directly from the `localhost:5758` address, since HTTPS is not required.
