### ISSUE TITLE
s3 storage should not require access keys

### ISSUE THREAD

**Issue by vincentgna** [valentindeaconu/terralist#28]
if access keys are not provided, the default aws go sdk credential chain should be used (using STS / Ec2 IAM role or EKS svc role)

ref: https://docs.aws.amazon.com/sdk-for-go/api/aws/defaults/#CredChain

**Comment by vincentgna** [comment]
I'm trying to understand the storage implementations:

- if local, just need to have the modules living next to terralist (for example I could push release to a separate git branch and have git-sync the module versions, each time I push a binary to the branch I post the new module description and path to terralist?)
- if s3, the API to post a module doesn't seem ready yet?

**Comment by valentindeaconu** [comment]
> if access keys are not provided, the default aws go sdk credential chain should be used (using STS / Ec2 IAM role or EKS svc role)

I don't think it's a good idea to use the default credentials chain by default (if the variables are missing). You can force that behavior by setting the `s3-access-key-id` and `s3-secret-access-key` flags (or set `TERRALIST_S3_ACCESS_KEY_ID` and `TERRALIST_S3_SECRET_ACCESS_KEY` environment variables) to `${AWS_ACCESS_KEY_ID}` or `${AWS_SECRET_ACCESS_KEY}` values, which will instruct Terralist to read the values from those environment variables. 

I think that's not a good idea because there might be some cases in which you want to use separate S3 buckets for different workflows (e.g.: an S3 bucket for modules and an S3 bucket for providers). If we fall back to the default credentials chain, Terralist will use those credentials transparently which may lead to future problems.

Why do you think this behavior will be useful?

> * just need to have the modules living next to terralist (for example I could push release to a separate git branch and have git-sync keep a copy of that branch in the local fs for terralist, each time I push a binary to the branch, git-sync would pull it and my CI would need to HTTP POST the new module description and path to terralist?)
The local resolver is not yet implemented, but yes, this was the intention. To have a mounted volume in which modules and providers can be stored and from where they can be served. I didn't design it that further, but I think for modules you can use git to sync their code and serve them from the local git clone, but that kind of beats the purpose of the versioning. If you want to use it with git, you can look into the `proxy` resolver. The main purpose for the `proxy` resolver was to "rename" the source field in Terraform. For example, let's say you've a git repository "my-org/my-tf-module" that stores your Terraform module. With plain git, you can fetch it directly into Terraform with:
```
git@github.com:my-org/my-tf-module.git?ref=<branch-or-tag>
```
If your Terralist instance is set to `proxy` mode, it will store the download URL for this module exactly like that, and when a request arrives, it will forward this URL to Terraform, and Terraform will handle it.
So, your module definition will be changed from:
```
module "my-module-instance" {
  source  = "git@github.com:my-org/my-tf-module.git?ref=<branch-or-tag>"
  ...
}
```
To:
```
module "my-module-instance" {
  source  = "registry.example.com/my-org/my-module/provider"
  version = "<the version value you under which uploaded the module>"
  ...
}
```

> * if s3, the API to post a module doesn't seem ready yet?
The S3 resolver for modules is completely functional, at least at an beta level, I didn't put it yet under real-world test load.

> but none of the above is possible from CI without API Key support
Exactly, you will need to generate an API key. You can insert an API key directly into the database. The management of API keys will be handled from the web interface, I am not planning to develop a REST API to generate an API key. Keep in mind that an API key is directly linked (and dependent) to an Authority, so you will have to create one too. An authority holds the public GPG key, which is served to Terraform to verify the signatures. In the near future, it will be linked to a namespace: so an authority determines the namespace under which you can upload modules and providers using an authority API key.

> in short, at this point terralist can't really be used yet?
Not really at a production level. The modules registry is pretty stable, but you have to manually insert an authority and an API key and only upload modules under this authority. Multiple authorities are not yet tested.

**Comment by vincentgna** [comment]
> You can force that behavior by setting the s3-access-key-id and s3-secret-access-key flags (or set TERRALIST_S3_ACCESS_KEY_ID and TERRALIST_S3_SECRET_ACCESS_KEY environment variables) to ${AWS_ACCESS_KEY_ID} or ${AWS_SECRET_ACCESS_KEY} values, which will instruct Terralist to read the values from those environment variables.

I'm talking about Temporary credentials using STS, having worked at several larger fintech companies, it's unacceptable to have long lived credentials.

**Comment by valentindeaconu** [comment]
I see what are you suggesting now. I didn't take that into consideration. I agree with your suggestion and I will put this on the roadmap.

**Comment by vincentgna** [comment]
thank you, also wanted to mention that access across accounts / resources is usually done through IAM roles or Resource Access Manager on AWS (I've mostly used IAM Roles and trust relationships rather than RAM though so I'm not so familiar with RAM)
