### ISSUE TITLE
docs on GitHub OAuth config

### ISSUE THREAD

**Issue by vincentgna** [valentindeaconu/terralist#29]
I wasn't very familiar with the GitHub OAuth configuration and device workflow, took me a good while to figure out the callback url should be to the `v1/api/auth/redirect` path on your terralist host

also, it's not clear how the CI will get token non-interactively?

```sh
$ terraform login registry.example.com
Terraform will request an API token for registry.example.com using OAuth.

This will work only if you are able to use a web browser on this computer to
complete a login process. If not, you must obtain an API token by another
means and configure it in the CLI configuration manually.
```

**Comment by vincentgna** [comment]
RE: the API service to generate keys for CI doesn't seem to have any HTTP routes yet, correct?

**Comment by valentindeaconu** [comment]
> I wasn't very familiar with the GitHub OAuth configuration and device workflow, took me a good while to figure out the callback url should be to the `v1/api/auth/redirect` path on your terralist host

I am really sorry for this, there's no documentation yet for getting started, but I have put that on the roadmap.

> also, it's not clear how the CI will get token non-interactively?

The maintainer will have to generate an API key from the web interface, then pass it to the CI as a secret.

> RE: the API service to generate keys for CI doesn't seem to have any HTTP routes yet, correct?
>
> edit: re-read the planned feature list, and although you already have code to validate the API key, the API key feature is still planned so I guess that's why there's no way to actually call the `grant(int expire..)` method

No, there's no route because I wanted to add that feature to the web interface. I manually inserted mine into the database. The ID (UUID v4) of the ApiKey object is the API key, and needs to be set as `x-api-key:<the-uuid-value>`. 

> I'd love to contribute, but I'm still learning the codebase

Thank you for your interest, feel free to ask any questions, and I will answer them as fast as I can.
